const ADMIN_ROLE = 'ADMIN_ROLE';
const USER_ROLE = 'USER_ROLE';
const SALES_ROLE = 'SALES_ROLE';
const ROLES = ['ADMIN_ROLE', 'USER_ROLE', 'SALES_ROLE'];

module.exports = {
  ADMIN_ROLE,
  USER_ROLE,
  SALES_ROLE,
  ROLES
}